[[language]]
name = "rust"
auto-format = true

[[language]]
name = "python"
config = { "pylsp" = { "plugins" = { "pycodestyle" = { "maxLineLength" = 89, "ignore" = [ "W503", "W293", "E303" ] }}}}
formatter = { command = "black", args = ["--quiet", "--line-length=88", "-"] }
auto-format = true
