[options]
  filemanager = "nerdtree"
  filetree_direction = "left"

  colorscheme = "gruvbox"
  colorscheme_bg = "dark"

  statusline_separator = "arrow"
  statusline_separator = "arrow"

  buffer_index_type = 4

  enable_tabline_filetype_icon = true
  enable_statusline_mode = false

  bootstrap_before = 'config#before'
  #bootstrap_after = 'config#after'

  enable_vimfiler_gitstatus = true

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "checkers"

[[layers]]
  name = "tmux"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "lang#python"
