[options]
  filemanager = "nerdtree"
  filetree_direction = "left"

  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  enable_guicolors = true

  bootstrap_before = 'config#before'
  #bootstrap_after = 'config#after'

  enable_vimfiler_gitstatus = true

  enable_statusline_mode = true
  statusline_left_sections = [
       'winnr',
       'filename',
       'version control info',
  ]
  statusline_right_sections = [
    'cursorpos',
  ]


[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "checkers"

[[layers]]
  name = "tmux"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "lang#python"
